import { useEffect, useMemo, useState } from 'react'
import { cet6Words } from './data/words'
import { vlogVideos } from './data/videos'
import { dailySavingsTarget } from './domain/savings'
import { buildTodayTasks, type Task } from './domain/schedule'
import { calculateStreak } from './domain/streak'
import { db, exportBackup, getLog, importBackup, saveLog, type DailyLog, type GroupReview } from './lib/db'

type Page = 'today' | 'group' | 'media' | 'fitness' | 'english' | 'wordbook' | 'reading' | 'review'
type Props = { log: DailyLog; updateLog: (next: DailyLog) => Promise<void>; toggleTask: (id: string) => Promise<void>; done: (id: string) => boolean; tasks: Task[] }
const labels: Record<Page, string> = { today: '今日行动', group: '兼职群', media: '新媒体', fitness: '健身', english: '英语学习', wordbook: '生词本', reading: '阅读', review: '每日复盘' }
const icons: Record<Page, string> = { today: '☀️', group: '💼', media: '📣', fitness: '💪', english: '📚', wordbook: '🗂️', reading: '📖', review: '📋' }
const extraParts = ['胸', '背', '肩', '手臂', '腿', '核心', '足球 / 有氧']
function key(date = new Date()) { return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}` }
function sameWeek(dateKey: string, today: Date) { const value = new Date(`${dateKey}T12:00:00`); const start = new Date(today); start.setDate(today.getDate() - ((today.getDay() + 6) % 7)); start.setHours(0,0,0,0); const end = new Date(start); end.setDate(start.getDate() + 7); return value >= start && value < end }
function speak(text: string) { window.speechSynthesis?.cancel(); window.speechSynthesis?.speak(new SpeechSynthesisUtterance(text)) }
function download(name: string, content: string) { const url = URL.createObjectURL(new Blob([content], { type: 'application/json' })); const a = document.createElement('a'); a.href=url; a.download=name; a.click(); URL.revokeObjectURL(url) }

export default function App() {
 const [page,setPage]=useState<Page>('today'), [drawer,setDrawer]=useState(false), [log,setLog]=useState<DailyLog>({date:key(),completedTaskIds:[]}), [logs,setLogs]=useState<DailyLog[]>([])
 const today=new Date(), todayKey=key(today), tasks=useMemo(()=>buildTodayTasks(today),[todayKey])
 const refresh=async()=>{ setLog(await getLog(todayKey)); setLogs(await db.dailyLogs.toArray()) }
 useEffect(()=>{ void refresh(); if('serviceWorker' in navigator) navigator.serviceWorker.register(`${import.meta.env.BASE_URL}sw.js`) },[])
 const updateLog=async(next:DailyLog)=>{ await saveLog(next); await refresh() }
 const toggleTask=async(id:string)=>{ const current=await getLog(todayKey); const completedTaskIds=current.completedTaskIds.includes(id)?current.completedTaskIds.filter(x=>x!==id):[...current.completedTaskIds,id]; await updateLog({...current,completedTaskIds}) }
 const done=(id:string)=>log.completedTaskIds.includes(id)
 const totalSavings=logs.reduce((sum,item)=>sum+(item.money?.savings??0)+(item.dailyReview?.saved??0)+(item.weeklyLivingSaved?200:0),0)
 const groupMembers=logs.reduce((sum,item)=>sum+(item.groupReview?.newMembers??0),778)
 const weeklyProfit=logs.filter(item=>sameWeek(item.date,today)).reduce((sum,item)=>sum+(item.groupReview?.netProfit??0),0)
 const status=new Map(logs.map(item=>[item.date,buildTodayTasks(new Date(`${item.date}T12:00:00`)).every(task=>item.completedTaskIds.includes(task.id))]))
 const streak=calculateStreak(todayKey,status), props={log,updateLog,toggleTask,done,tasks}
 const nav=(item:Page)=>{setPage(item);setDrawer(false)}
 return <div className="app-shell"><aside className={`drawer ${drawer?'open':''}`}><div className="brand"><span>✦</span><strong>我的行动工作台</strong><small>Action, not anxiety.</small></div>{(Object.keys(labels) as Page[]).map(item=><button key={item} className={page===item?'nav active':'nav'} onClick={()=>nav(item)}><span>{icons[item]}</span>{labels[item]}</button>)}<div className="drawer-footer">本机保存 · 周日备份</div></aside>{drawer&&<button className="scrim" onClick={()=>setDrawer(false)} />}<main><header><button className="menu" onClick={()=>setDrawer(true)}>☰</button><div><p>{new Intl.DateTimeFormat('zh-CN',{month:'long',day:'numeric',weekday:'long'}).format(today)}</p><h1>{labels[page]}</h1></div><span className="streak">🔥 {streak}</span></header>{page==='today'&&<Today tasks={tasks} done={done} toggleTask={toggleTask} go={nav} totalSavings={totalSavings}/>} {page==='group'&&<Group {...props} members={groupMembers} profit={weeklyProfit}/>} {page==='media'&&<Media {...props}/>} {page==='fitness'&&<Fitness {...props}/>} {page==='english'&&<English {...props}/>} {page==='wordbook'&&<Wordbook logs={logs}/>} {page==='reading'&&<Reading {...props}/>} {page==='review'&&<Review {...props} totalSavings={totalSavings} logs={logs} onExport={async()=>download(`行动工作台-${todayKey}.json`,await exportBackup())} onImport={async file=>{if(confirm('导入会覆盖当前本机数据，确定继续吗？')){await importBackup(await file.text());await refresh()}}}/>}</main></div>
}
function Today({tasks,done,toggleTask,go,totalSavings}:{tasks:Task[];done:(id:string)=>boolean;toggleTask:(id:string)=>Promise<void>;go:(page:Page)=>void;totalSavings:number}) { const complete=tasks.every(task=>done(task.id)); return <section className="page"><div className="hero"><span>{complete?'✨':'🎯'}</span><div><p>{complete?'今天全部完成，去休息吧。':'先完成今天的行动，再考虑别的。'}</p><strong>{tasks.filter(task=>done(task.id)).length} / {tasks.length} 已完成</strong></div></div><div className="stat-row"><article><small>累计存钱</small><b>¥{totalSavings}</b><em>目标 ¥10,000</em></article><article><small>今日规则</small><b>全部完成</b><em>才延续连续天数</em></article></div><h2>今天要做</h2><div className="task-list">{tasks.map(task=><button className={`task ${done(task.id)?'done':''}`} key={task.id} onClick={()=>done(task.id)?void toggleTask(task.id):go(task.area==='兼职群'?'group':task.area==='英语'?'english':task.area==='健身'?'fitness':task.area==='新媒体'?'media':task.area==='阅读'?'reading':'review')}><span className="checkbox">{done(task.id)?'✓':''}</span><span><small>{task.area}</small>{task.title}</span><b>›</b></button>)}</div></section> }
function Group({log,updateLog,toggleTask,done,tasks,members,profit}:Props&{members:number;profit:number}){const [form,setForm]=useState<GroupReview>(log.groupReview??{posts:0,merchants:0,leads:0,newMembers:0,netProfit:0});const taskList=tasks.filter(t=>t.area==='兼职群');const save=async()=>{const current=await getLog(log.date);await updateLog({...current,groupReview:form,completedTaskIds:current.completedTaskIds.includes('group-review')?current.completedTaskIds:[...current.completedTaskIds,'group-review']})};return <section className="page"><div className="stat-row"><article><small>群人数</small><b>{members} / 900</b><progress value={members} max="900"/></article><article><small>本周真实净利润</small><b>¥{profit}</b><em>只记到手净利润</em></article></div><h2>每日运营闭环</h2><div className="action-grid">{taskList.filter(t=>t.id!=='group-review').map(t=><button key={t.id} className={done(t.id)?'action done':'action'} onClick={()=>void toggleTask(t.id)}><span>{done(t.id)?'✓':'○'}</span>{t.title}</button>)}</div><h2>晚上复盘</h2><div className="form-card">{([['posts','发布帖子数'],['merchants','联系商家数'],['leads','有效评论 / 私信数'],['newMembers','新进群人数'],['netProfit','真实净利润（元）']]as const).map(([field,label])=><label key={field}>{label}<input type="number" min="0" value={form[field]||''} placeholder="0" onChange={e=>setForm({...form,[field]:e.target.value===''?0:Number(e.target.value)})}/></label>)}<button className="primary" onClick={()=>void save()}>保存并完成复盘</button></div></section>}
function Media({log,updateLog,done,tasks}:Props){const task=tasks.find(t=>t.area==='新媒体');const[note,setNote]=useState(log.mediaNote??'');if(!task)return <Empty title="今天没有新媒体任务" text="周四招新、周五内容、周六私域跟进。"/>;return <section className="page"><div className="hero"><span>📣</span><div><p>今天只做一件事</p><strong>{task.title}</strong></div></div><div className="form-card"><label>完成备注（可选）<textarea value={note} onChange={e=>setNote(e.target.value)} /></label><button className="primary" onClick={async()=>{const current=await getLog(log.date);await updateLog({...current,mediaNote:note,completedTaskIds:done(task.id)?current.completedTaskIds:[...current.completedTaskIds,task.id]})}}>完成今日新媒体动作</button></div></section>}
function Fitness({log,updateLog,toggleTask,done,tasks}:Props){const task=tasks.find(t=>t.area==='健身');const extras=log.extraFitness??[];const toggleExtra=async(part:string)=>{const current=await getLog(log.date);const next=current.extraFitness?.includes(part)?current.extraFitness.filter(x=>x!==part):[...(current.extraFitness??[]),part];await updateLog({...current,extraFitness:next})};return <section className="page"><div className="hero"><span>💪</span><div><p>{task?'今日训练':'今天是恢复日'}</p><strong>{task?.title??'可选加练，不强制'}</strong></div></div>{task&&<div className="form-card"><button className="primary" onClick={()=>void toggleTask(task.id)}>{done(task.id)?'已完成训练 ✓':'完成今日训练'}</button></div>}<h2>加一个计划（可选）</h2><div className="action-grid">{extraParts.map(part=><button key={part} className={extras.includes(part)?'action done':'action'} onClick={()=>void toggleExtra(part)}><span>{extras.includes(part)?'✓':'＋'}</span>{part}</button>)}</div>{extras.length>0&&<p className="hint">今日额外计划：{extras.join('、')}。它不影响连续天数。</p>}</section>}
function English({log,updateLog,done}:Props){const [limit,setLimit]=useState(5),[flipped,setFlipped]=useState<string|null>(null),[steps,setSteps]=useState([false,false]),[note,setNote]=useState(log.englishNote??'');const words=log.learnedWords??{},video=vlogVideos[new Date().getDate()%vlogVideos.length],list=cet6Words.slice(0,limit);const mark=async(id:string,status:'known'|'review')=>{const current=await getLog(log.date);const learnedWords={...(current.learnedWords??{}),[id]:status};const completedTaskIds=list.slice(0,5).every(w=>learnedWords[w.id])&&!current.completedTaskIds.includes('english-words')?[...current.completedTaskIds,'english-words']:current.completedTaskIds;await updateLog({...current,learnedWords,completedTaskIds})};const finish=async()=>{const current=await getLog(log.date);await updateLog({...current,englishNote:note,completedTaskIds:done('english-vlog')?current.completedTaskIds:[...current.completedTaskIds,'english-vlog']})};return <section className="page"><div className="stat-row"><article><small>今日六级词</small><b>{list.slice(0,5).filter(w=>words[w.id]).length}/5</b><em>{done('english-words')?'已完成 ✓':'完成前 5 个'}</em></article><article><small>今日 vlog</small><b>{video.minutes} min</b><em>{video.tag}</em></article></div><h2>六级词汇</h2><div className="word-list">{list.map(w=><article className="word-card" key={w.id} onClick={()=>setFlipped(flipped===w.id?null:w.id)}><div><b>{w.word}</b><small>{w.phonetic}</small></div><button onClick={e=>{e.stopPropagation();speak(w.word)}}>🔊</button><p><strong>{w.meaning}</strong><br/>{w.example}</p><footer><button onClick={e=>{e.stopPropagation();void mark(w.id,'review')}}>生词</button><button onClick={e=>{e.stopPropagation();void mark(w.id,'known')}}>会了 ✓</button></footer></article>)}</div>{limit<cet6Words.length&&<button className="secondary wide" onClick={()=>setLimit(Math.min(limit+5,cet6Words.length))}>继续背 5 个词</button>}<h2>vlog 磨耳朵</h2><article className="video-card"><div className="video-placeholder">▶<small>{video.tag} · {video.minutes} min</small></div><h3>{video.title}</h3><p>@{video.creator}</p><div className="video-actions"><a href={`https://player.bilibili.com/player.html?bvid=${video.bvid}&page=1`} target="_blank">播放视频</a><a href={`https://www.bilibili.com/video/${video.bvid}/`} target="_blank">打开原视频</a></div></article><div className="form-card"><p>本条视频建议积累：</p><div className="phrase-list">{video.phrases.map(x=><span key={x}>{x}</span>)}</div><p>跟读两句：</p>{video.shadowing.map((x,i)=><label className="check-line" key={x}><input type="checkbox" checked={steps[i]} onChange={()=>setSteps(steps.map((v,n)=>n===i?!v:v))}/>{x}</label>)}<label>用自己的话写 1 句<textarea value={note} placeholder="I want to visit this place one day." onChange={e=>setNote(e.target.value)}/></label><button className="primary" disabled={!steps.every(Boolean)||!note.trim()} onClick={()=>void finish()}>{done('english-vlog')?'已完成 vlog ✓':'完成今日 vlog 学习'}</button></div></section>}
function Reading({tasks,done,toggleTask}:Props){const task=tasks.find(t=>t.id==='reading-30');return <section className="page"><div className="hero"><span>📖</span><div><p>每天留半小时给自己</p><strong>阅读 30 分钟</strong></div></div><div className="form-card"><p>纸书、电子书、英文读物都可以。读完再打卡，不追求一次读很多。</p><button className="primary" onClick={()=>task&&void toggleTask(task.id)}>{done('reading-30')?'今日阅读已完成 ✓':'完成 30 分钟阅读'}</button></div></section>}function Wordbook({logs}:{logs:DailyLog[]}){const reviewIds=new Set(logs.flatMap(log=>Object.entries(log.learnedWords??{}).filter(([,v])=>v==='review').map(([id])=>id)));const words=cet6Words.filter(word=>reviewIds.has(word.id));return <section className="page"><div className="hero"><span>🗂️</span><div><p>从英语学习里自动收集</p><strong>{words.length} 个生词</strong></div></div>{words.length?<div className="word-list">{words.map(w=><article className="word-card" key={w.id}><div><b>{w.word}</b><small>{w.phonetic}</small><p>{w.meaning}</p></div><button onClick={()=>speak(w.word)}>🔊</button></article>)}</div>:<Empty title="生词本还是空的" text="在英语词卡上点“生词”，它会自动出现在这里。"/>}</section>}
function Review({log,updateLog,totalSavings,logs,onExport,onImport}:Props&{totalSavings:number;logs:DailyLog[];onExport:()=>Promise<void>;onImport:(file:File)=>Promise<void>}){const [saved,setSaved]=useState(log.dailyReview?.saved??0),[reflection,setReflection]=useState(log.dailyReview?.reflection??''),[tomorrow,setTomorrow]=useState(log.dailyReview?.tomorrow??'');const weeklyLog=logs.find(item=>sameWeek(item.date,new Date())&&item.weeklyLivingSaved);const target=dailySavingsTarget(totalSavings,new Date());const save=async()=>{const current=await getLog(log.date);await updateLog({...current,dailyReview:{saved,reflection,tomorrow}})};const toggleLiving=async()=>{if(weeklyLog&&weeklyLog.date!==log.date){await saveLog({...weeklyLog,weeklyLivingSaved:false});window.location.reload();return}const current=await getLog(log.date);await updateLog({...current,weeklyLivingSaved:!current.weeklyLivingSaved})};const days=logs.filter(item=>item.dailyReview||item.weeklyLivingSaved).sort((a,b)=>b.date.localeCompare(a.date)).slice(0,7);return <section className="page"><div className="stat-row"><article><small>累计存钱</small><b>¥{totalSavings}</b><progress value={Math.min(totalSavings,10000)} max="10000"/></article><article><small>每日额外存钱目标</small><b>¥{target}</b><em>每周 ¥500 中扣除生活费 ¥200 后计算</em></article></div><h2>每天复盘</h2><div className="form-card"><label>今天存了多少钱<input type="number" min="0" value={saved||''} placeholder="0" onChange={e=>setSaved(e.target.value===''?0:Number(e.target.value))}/></label><label>今天的复盘<textarea value={reflection} placeholder="今天什么做得好 / 卡在哪里？" onChange={e=>setReflection(e.target.value)}/></label><label>明天最重要的一件事<textarea value={tomorrow} placeholder="只写一件" onChange={e=>setTomorrow(e.target.value)}/></label><button className="primary" onClick={()=>void save()}>保存今日复盘</button><button className="secondary" onClick={()=>void toggleLiving()}>{weeklyLog?'取消本周生活费 ¥200':'本周生活费存 ¥200'}</button></div><h2>近 7 天存钱明细</h2><div className="form-card">{days.length?days.map(item=><div className="money-row" key={item.date}><span>{item.date}</span><b>¥{(item.dailyReview?.saved??0)+(item.weeklyLivingSaved?200:0)}</b><small>{item.weeklyLivingSaved?'含生活费 ¥200':''}</small></div>):<p>还没有存钱记录。每天填“额外存钱”，生活费 ¥200 单独记一次。</p>}</div><h2>本机备份</h2><div className="form-card"><button className="secondary" onClick={()=>void onExport()}>导出 JSON 备份</button><label className="file">导入备份<input type="file" accept="application/json" onChange={e=>{const file=e.target.files?.[0];if(file)void onImport(file)}}/></label></div></section>}function Empty({title,text}:{title:string;text:string}){return <section className="page empty"><span>🌿</span><h2>{title}</h2><p>{text}</p></section>}
